version: '3.8'

services:
  web:
    build: .
    restart: always
    command: gunicorn --bind 0.0.0.0:5000 app:app
    expose:
      - 5000
  nginx:
    build: ./nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - web
