- name: Run brew link
  command: brew link --overwrite openssl@1.1

- name: Install packages with Linuxbrew
  homebrew:
    name:
      - bash
      - zsh
      - rg
      - fd
      - fzf
      - fzy
      - jq
      - yq
    state: present
    path: "{{ linuxbrew_dir }}"
    update_homebrew: false

- name: Install packages with Linuxbrew with --HEAD option
  homebrew:
    name:
      - nvim
    state: present
    path: "{{ linuxbrew_dir }}"
    install_options:
      - HEAD
    update_homebrew: false
